### ISSUE TITLE
Joi@10.6.1 fails w/ Buffer error

### ISSUE THREAD

**Issue by anatolikurtsevich** [jeffbski/joi-browser#21] opened 2017-07-12 22:53 UTC
I've updated to joi-browser@10.6.1 and now the following schema ```const schema = Joi.string().regex(/^[^*;:"'`()@&,]+$/)``` fails with Buffer error when I do ```schema.validate("Test*")```.

**Comment by the-spyke** [comment] 2017-07-13 06:39
Looks like the result #20 with setting `Buffer` to `mock` in Webpack's config.

**Comment by jeffbski** [comment] 2017-07-17 15:35
Thanks for reporting this. 

I am adding a karma test based on your example above so we can fix this.

I thought if we just set Buffer to true then it would fix it but it throws an error "Buffer is not included.". Do I need to import or include some polyfill in the config or something besides just setting the config flag to true?

**Comment by the-spyke** [comment] 2017-07-17 17:53
@jeffbski It seems working if I set `Buffer` to `true` and rebuild.

**Comment by jeffbski** [comment] 2017-07-18 01:24
@the-spyke wow, that's strange. At first I thought it was only with karma/phantom but it seems to be doing it from karma/ChromeHeadless too. 

I have pushed up my branch if anyone has ideas
https://github.com/jeffbski/joi-browser/tree/fix-missing-buffer

**Comment by the-spyke** [comment] 2017-07-25 15:13
@jeffbski It shouldn't be strange. From Webpack's manual:
```
true: Provide a polyfill.
```

**Comment by jeffbski** [comment] 2017-07-25 18:23
@the-spyke I meant that it is strange that I get an error when I try to do the same thing that worked for you. I agree that it should just work by setting that true. I just don't know how to fix the error I am seeing. I have everything up in the branch I linked above and running `npm test` throws the error above.

**Comment by kamronbatman** [comment] 2017-07-26 00:05
I can't wait for this to be fixed and the newest version supported.

**Comment by jeffbski** [comment] 2017-07-26 00:41
@kamronbatman joi-browser@10.6.1 is available, I think the only issue now is if one wants to use any joi features that rely on buffers like the example above. For some reason, when I enable the buffer polyfill a new error is thrown when one tries to use those features but yet it works for @the-spyke. 

So I am at a loss as to how to resolve this with regards to the buffer polyfill. 

Ideas are welcome, the branch is available here https://github.com/jeffbski/joi-browser/tree/fix-missing-buffer You can run the karma tests by running `npm test`

**Comment by kamronbatman** [comment] 2017-07-31 23:47
If Buffer doesn't exist, use this? https://www.npmjs.com/package/buffer

**Comment by kamronbatman** [comment] 2017-08-01 14:57
Correct, and I am using the newest webpack 2.x and babel.

**Comment by the-spyke** [comment] 2017-08-01 21:12
And I'm using Webpack 3.x.

**Comment by jeffbski** [comment] 2017-08-02 13:32
Thanks. Maybe I just need to upgrade these and everything will start working? That will be my next attempt.

**Comment by UchihaVeha** [comment] 2017-08-03 10:00
I have same Buffer error, how fix it?

**Comment by kamronbatman** [comment] 2017-08-03 17:20
Since I am using webpack with babel-loader (React/ES6), I just imported the newest joi, set webpack configuration to this:
```javascript
  node: {
    Buffer: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    crypto: 'empty',
    dns: 'empty',
  },
```
And it worked!

Also I made a mistake, I am actually on Webpack 3.4.1.

**Comment by jeffbski** [comment] 2017-08-04 13:29
@kamronbatman Thanks for sharing, that is good news.

**Comment by jmgarciaromero** [comment] 2017-09-15 13:43
Hi guys, I'm struggling to make it work. I'm using webpack@2.7.0, joi@10.6.0 and joi-browser@10.6.1, I have set `Buffer` to `true` as well, but the exception is always there:

```javascript
Uncaught Error: Buffer is not included.
    at new Buffer (common.017f30b28eee09cd4e11.js:30875)
    at Object.internals.escapeHtmlChar (common.017f30b28eee09cd4e11.js:32017)
    at Object.exports.escapeHtml (common.017f30b28eee09cd4e11.js:31989)
    at Object.exports.escapeHtml (common.017f30b28eee09cd4e11.js:30747)
    at common.017f30b28eee09cd4e11.js:33100
    at String.replace (<anonymous>)
    at _class.toString (common.017f30b28eee09cd4e11.js:33096)
    at processErrors (common.017f30b28eee09cd4e11.js:33138)
    at Object.exports.process (common.017f30b28eee09cd4e11.js:33160)
    at _class._validateWithOptions (common.017f30b28eee09cd4e11.js:32708)
```

I'm about to give up and go back to the previous version, but in that case I have the problem described in [this issue](https://github.com/hapijs/joi/issues/1301)

**Comment by jeffbski** [comment] 2017-09-15 18:02
So it sounds like this is an issue in webpack@2 that is fixed in webpack@3, if I am understanding correctly. 

Was anyone able to get it working with webpack@2?

**Comment by jmgarciaromero** [comment] 2017-09-28 16:28
I just found out that my problem is linked to the existence of a question mark in the custom error message

`
selfEmployed: Joi.boolean().label('Are you self employed?'),
`

If I remove the question mark everything is fine...

**Comment by kamronbatman** [comment] 2017-09-28 17:58
@jmgarciaromero Does your issue go away with webpack 3.x without removing the question mark?

**Comment by jmgarciaromero** [comment] 2017-09-28 18:53
No it doesn't go away. We're using webpack 3.6.0. 

I have tried everything that's been suggested in this thread but so far the only way to avoid the Buffer error is by removing special characters from the custom error message.

I also opened [this issue](https://github.com/hapijs/joi/issues/1317) for the Joi team.

**Comment by frosato-ekino** [comment] 2017-10-05 09:40
@jeffbski @jmgarciaromero 
Any updates about this issue ? 
Any way to fix this without touching webpack config ?

**Stack:** 
webpack "3.5.1", 
joi-browser: "^10.6.1",

**Code:**
```js
const urlRegex = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=+$,\w]+@)?[A-Za-z0-9.-]+|(?:www\.|[-;:&=+$,\w]+@)[A-Za-z0-9.-]+)((?:\/[+~%/.\w\-_]*)?\??(?:[-+=&;%@.\w_]*)#?(?:[.!/\\\w]*))?)/

Joi.string().regex(urlRegex)
```
**Error:** 
```js 
Uncaught Error: Buffer is not included.
```
Error is thrown when typing the '/' of 'http:/'

**Comment by jmgarciaromero** [comment] 2017-10-05 09:59
The guys from Joi suggest it might be a bundling issue. As soon as they find out that you're using Joi for the client side and the issue is not reproducible on their target environment they immediately deny support, which I kind of understand even though their manners are not quite correct sometimes...

Take a look at Joi issue [#665](https://github.com/hapijs/joi/issues/665)

Sorry for not being of much help here...

**Comment by frosato-ekino** [comment] 2017-10-05 10:21
@jmgarciaromero Thanks for your quick answer! 
It's such a pity they are ignoring client side. Without regexp's validation the library become pointless. I'll let you know if i find a way to make it work.

**Comment by jmgarciaromero** [comment] 2017-10-24 14:15
I managed to build joi-browser with joi v12 or v13 (thanks to the joi team for that...) and the "Buffer not included" error is gone. I had to upgrade dependencies to use webpack 2 and karma-webpack 2.

Unfortunately when I run the tests I get an unexpected error output linked to the email validation

```javascript
      × should validate a valid object
        PhantomJS 2.1.1 (Windows 8 0.0.0)
      Expected { [ValidationError: child "email" fails because ["email" must be a valid email]] isJoi: true, name: 'ValidationError', details: [ { message: '"email" must be a valid email', path: [ 'email' ], type: 'string.email', context: { value: 'foo@bar.com'
, key: 'email', label: 'email' } } ], _object: { username: 'abc', email: 'foo@bar.com', birthyear: 1994 }, annotate: [Function] } to not exist
      assert@src/basic.kmocha.js:2875:27
      toNotExist@src/basic.kmocha.js:3873:28
      src/basic.kmocha.js:15118:46
      _validateWithOptions@src/basic.kmocha.js:6516:40
      validate@src/basic.kmocha.js:6544:57
      src/basic.kmocha.js:15116:22
```
No clue about it... out of my basic expertise...

**Comment by jeffbski** [comment] 2017-10-24 16:08
Thanks for all your hard work on this @jmgarciaromero. I feel your pain. It was nice when joi natively supported both node.js and the browser. I tried to help by creating this package (which seemed to work for a while there), but now these errors that have cropped up are also outside of my expertise. Arrgh.

**Comment by Marsup** [comment] 2017-10-24 17:15
@jmgarciaromero can you provide a fork with bumped versions ?

**Comment by kamronbatman** [comment] 2017-10-24 19:52
@Marsup, I am very happy you saw this and are able to help!  Thank you!  I hope in the future joi will support React in some way shape or form.

**Comment by jmgarciaromero** [comment] 2017-10-27 07:24
Sorry guys for my late reply, you caught me in the middle of a move. Fork has been created on github, my first fork actually... should go and buy some champagne...

https://github.com/jmgarciaromero/joi-browser.git

I did not do anything special, just upgrade to joi 13.0.1, webpack 2.7.0 and karma-webpack 2.0.5 and adjust the config.

**Comment by Marsup** [comment] 2017-11-01 19:26
It's failing because Buffer is mocked, and `isemail` is using `Buffer.byteLength` all over the place, you have to at least unmock this one.

**Comment by jeffbski** [comment] 2017-11-01 20:42
Thanks @Marsup I think that's what started this whole conversation. When we tried to include the buffer polyfill it wasn't quite working, but it looked like it was on newer versions of the build tools.

**Comment by Marsup** [comment] 2017-11-01 21:46
When set to true it seems to work, was there any problem with that ?

**Comment by jeffbski** [comment] 2017-11-01 23:53
@Marsup it wasn't working at least with the old webpack. https://github.com/jeffbski/joi-browser/issues/21#issuecomment-315930941 

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'global.TYPED_ARRAY_SUPPORT')
  at src/basic.kmocha.js:13518
```

I can try @jmgarciaromero's upgraded versions and see if that passes.

**Comment by jeffbski** [comment] 2017-11-02 00:20
@jmgarciaromero's upgrade looks promising, but there's still some work to get it running with Karma now (npm test fails). Hopefully using the newer version of these tools will solve the issue. 

Current error in npm test which runs Karma is

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' /Users/jeff/projects/joi-browser/src/basic.kmocha.js in /Users/jeff/projects/joi-browser

So I guess something needs to change in my karma config with the upgrades.

**Comment by Marsup** [comment] 2017-11-02 09:24
It works for me on his fork, just have to enable buffers.

**Comment by jeffbski** [comment] 2017-11-02 11:27
I have pulled fork into a branch (https://github.com/jeffbski/joi-browser/tree/jmgarciaromero-master) and enabled buffers with Buffer: true and I am much closer but still having one test failure running `npm test`. 

```
START:
  Joi
    basic schema
      ✖ should validate a valid object
      ✔ should error with missing username
      ✔ should error with invalid email
      ✔ should error with invalid year

Finished in 0.031 secs / 0.011 secs @ 06:18:15 GMT-0500 (CDT)

SUMMARY:
✔ 3 tests completed
✖ 1 test failed

FAILED TESTS:
  Joi
    basic schema
      ✖ should validate a valid object
        PhantomJS 2.1.1 (Mac OS X 0.0.0)
      Expected { [ValidationError: child "email" fails because ["email" must be a valid email]] isJoi: true, name: 'ValidationError', details: [ { message: '"email" must be a valid email', path: [ 'email' ], type: 'string.email', context: { value: 'test@iana.org', key: 'email', label: 'email' } } ], _object: { username: 'abc', email: 'test@iana.org', birthyear: 1994 }, annotate: [Function] } to not exist
      assert@src/basic.kmocha.js:2875:27
      toNotExist@src/basic.kmocha.js:3873:28
      src/basic.kmocha.js:17135:46
      _validateWithOptions@src/basic.kmocha.js:6518:40
      validate@src/basic.kmocha.js:6546:57
      src/basic.kmocha.js:17133:22
```

**Comment by Marsup** [comment] 2017-11-02 11:52
To allow me some debugging I switched to karma chrome, might be why all my tests succeed. It doesn't make sense to keep using phantom imho.

**Comment by jeffbski** [comment] 2017-11-02 13:29
Thanks @Marsup phantom has always been a bit of a pain. I switched to ChromeHeadless so we can run in travis. 

Everything works properly now in ChromeHeadless. I am cutting a release for 13.0.1

**Comment by jeffbski** [comment] 2017-11-02 13:36
published joi-browser@13.0.1 to npm

Thanks @Marsup and @jmgarciaromero and to everyone on this issue for your help in resolving this.

**Closed by jeffbski** 2017-11-02 13:36 UTC
Labels: bug, help wanted

**Comment by jmgarciaromero** [comment] 2017-11-06 16:20
Great news! I'll give it a try once we finish moving to the new building and I can continue working as usual...

**Comment by kemal-smaylov** [comment] 2019-08-21 07:29
joi-browser which does not allow the use of many words in the label:
`Joi.required()
          .disallow('')
          // hack for joi-browser which does not allow the use of many words in the label.
          .label(field.title.split(' ').slice(0, 3).join(' '))`
